name: Check Advisories

on:
  # Triggers the workflow on push events only for the default branch
  pull_request:
  push:
    branches:
      - master

jobs:
  fetch:
    name: Check Advisories
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: pip install ./
      - name: Run Advisories Checks
        run: check_advisories --all
